FROM python:3.12.2-slim

RUN apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/*

WORKDIR /assistant

COPY requirements-dev.txt requirements-dev.txt

RUN pip install --upgrade pip \
 && pip install -r requirements-dev.txt

COPY app app
COPY bot bot
COPY alembic alembic
COPY alembic.ini alembic.ini
COPY db db
COPY config config
COPY run_migrations.sh run_migrations.sh

RUN chmod +x /assistant/run_migrations.sh