services:
  postgres:
    image: postgres:16.3-alpine
    env_file:
      - .env.dev
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    volumes:
      - .:/assistant  # Mount all source files for development
    working_dir: /assistant
    command: sh -c "./run_migrations.sh && watchmedo auto-restart --patterns='*.py' --recursive -- python3 -m app.main"  # Auto-reboot on changes
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    volumes:
      - .:/assistant  # Mount all source files for development
      - ./images_data:/assistant/bot/images
    working_dir: /assistant
    command: sh -c "./run_migrations.sh && exec watchmedo auto-restart --patterns='*.py' --recursive -- python3 -m bot.main"  # Auto-reboot on changes
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  redis:
    image: redis:7.4.0-alpine
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - app-network

volumes:
  postgres_data:
  images_data:

networks:
  app-network:
    driver: bridge
