services:
  postgres:
    image: postgres:16.3-alpine
    env_file:
      - .env.prod
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    env_file:
      - .env.prod
    volumes:
      - ./proxies.txt:/assistant/proxies.txt
    working_dir: /assistant
    command: sh -c "./run_migrations.sh && python3 -m app.main"
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  bot:
    build: .
    env_file:
      - .env.prod
    volumes:
      - ./images_data:/assistant/bot/images
    working_dir: /assistant
    command: sh -c "./run_migrations.sh && exec python3 -m bot.main"
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  redis:
    image: redis:7.4.0-alpine
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - app-network

volumes:
  postgres_data:
  images_data:

networks:
  app-network:
    driver: bridge
