"""Added new game Pin Out Master

Revision ID: 4741561ab172
Revises: 9ba9ef7ebda7
Create Date: 2024-09-18 11:00:09.916843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4741561ab172'
down_revision: Union[str, None] = '9ba9ef7ebda7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pin_out_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promo_code', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pin_out_master_created_at', 'pin_out_master', ['created_at'], unique=False)
    op.create_index(op.f('ix_pin_out_master_promo_code'), 'pin_out_master', ['promo_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pin_out_master_promo_code'), table_name='pin_out_master')
    op.drop_index('ix_pin_out_master_created_at', table_name='pin_out_master')
    op.drop_table('pin_out_master')
    # ### end Alembic commands ###
