"""Added new game Infected Frontier

Revision ID: 529afe77e729
Revises: e05720311f72
Create Date: 2024-09-19 11:03:49.349907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '529afe77e729'
down_revision: Union[str, None] = 'e05720311f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infected_frontier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promo_code', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_infected_frontier_created_at', 'infected_frontier', ['created_at'], unique=False)
    op.create_index(op.f('ix_infected_frontier_promo_code'), 'infected_frontier', ['promo_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_infected_frontier_promo_code'), table_name='infected_frontier')
    op.drop_index('ix_infected_frontier_created_at', table_name='infected_frontier')
    op.drop_table('infected_frontier')
    # ### end Alembic commands ###
