"""Added new game 'StoneAge'

Revision ID: 65293d769fd7
Revises: 2535e8a8f6bf
Create Date: 2024-09-05 17:57:35.502241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65293d769fd7'
down_revision: Union[str, None] = '2535e8a8f6bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stone_age',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promo_code', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stone_age_promo_code'), 'stone_age', ['promo_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stone_age_promo_code'), table_name='stone_age')
    op.drop_table('stone_age')
    # ### end Alembic commands ###
