"""remove safety columns from user table

Revision ID: 6daca0ba417e
Revises: 963649f22ad7
Create Date: 2024-09-26 18:38:12.861427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6daca0ba417e'
down_revision: Union[str, None] = '963649f22ad7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'daily_safety_keys_requests_count')
    op.drop_column('users', 'last_reset_date_safety_keys')
    op.drop_column('users', 'total_safety_keys_generated')
    op.drop_column('users', 'last_safety_keys_request_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_safety_keys_request_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('total_safety_keys_generated', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_reset_date_safety_keys', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('daily_safety_keys_requests_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
