"""Added 2 new games

Revision ID: 963649f22ad7
Revises: 529afe77e729
Create Date: 2024-09-19 19:27:22.820490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '963649f22ad7'
down_revision: Union[str, None] = '529afe77e729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('among_waterr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promo_code', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_among_waterr_created_at', 'among_waterr', ['created_at'], unique=False)
    op.create_index(op.f('ix_among_waterr_promo_code'), 'among_waterr', ['promo_code'], unique=False)
    op.create_table('factory_world',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promo_code', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_factory_world_created_at', 'factory_world', ['created_at'], unique=False)
    op.create_index(op.f('ix_factory_world_promo_code'), 'factory_world', ['promo_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_factory_world_promo_code'), table_name='factory_world')
    op.drop_index('ix_factory_world_created_at', table_name='factory_world')
    op.drop_table('factory_world')
    op.drop_index(op.f('ix_among_waterr_promo_code'), table_name='among_waterr')
    op.drop_index('ix_among_waterr_created_at', table_name='among_waterr')
    op.drop_table('among_waterr')
    # ### end Alembic commands ###
