"""Added Hide Ball to games list

Revision ID: 9ba9ef7ebda7
Revises: 652b3b420c9f
Create Date: 2024-09-14 13:46:30.450465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ba9ef7ebda7'
down_revision: Union[str, None] = '652b3b420c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hide_ball',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promo_code', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hide_ball_created_at', 'hide_ball', ['created_at'], unique=False)
    op.create_index(op.f('ix_hide_ball_promo_code'), 'hide_ball', ['promo_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hide_ball_promo_code'), table_name='hide_ball')
    op.drop_index('ix_hide_ball_created_at', table_name='hide_ball')
    op.drop_table('hide_ball')
    # ### end Alembic commands ###
