"""Add indexes on created_at

Revision ID: c4e02ccd4113
Revises: 65293d769fd7
Create Date: 2024-09-06 16:19:37.593341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4e02ccd4113'
down_revision: Union[str, None] = '65293d769fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_cafe_dash_created_at', 'cafe_dash', ['created_at'], unique=False)
    op.create_index('ix_chain_cube_2048_created_at', 'chain_cube_2048', ['created_at'], unique=False)
    op.create_index('ix_fluff_crusade_created_at', 'fluff_crusade', ['created_at'], unique=False)
    op.create_index('ix_gangs_wars_created_at', 'gangs_wars', ['created_at'], unique=False)
    op.create_index('ix_merge_away_created_at', 'merge_away', ['created_at'], unique=False)
    op.create_index('ix_mow_and_trim_created_at', 'mow_and_trim', ['created_at'], unique=False)
    op.create_index('ix_polysphere_created_at', 'polysphere', ['created_at'], unique=False)
    op.create_index('ix_stone_age_created_at', 'stone_age', ['created_at'], unique=False)
    op.create_index('ix_tile_trio_created_at', 'tile_trio', ['created_at'], unique=False)
    op.create_index('ix_train_miner_created_at', 'train_miner', ['created_at'], unique=False)
    op.create_index('ix_twerk_race_3d_created_at', 'twerk_race_3d', ['created_at'], unique=False)
    op.create_index('ix_zoopolis_created_at', 'zoopolis', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_zoopolis_created_at', table_name='zoopolis')
    op.drop_index('ix_twerk_race_3d_created_at', table_name='twerk_race_3d')
    op.drop_index('ix_train_miner_created_at', table_name='train_miner')
    op.drop_index('ix_tile_trio_created_at', table_name='tile_trio')
    op.drop_index('ix_stone_age_created_at', table_name='stone_age')
    op.drop_index('ix_polysphere_created_at', table_name='polysphere')
    op.drop_index('ix_mow_and_trim_created_at', table_name='mow_and_trim')
    op.drop_index('ix_merge_away_created_at', table_name='merge_away')
    op.drop_index('ix_gangs_wars_created_at', table_name='gangs_wars')
    op.drop_index('ix_fluff_crusade_created_at', table_name='fluff_crusade')
    op.drop_index('ix_chain_cube_2048_created_at', table_name='chain_cube_2048')
    op.drop_index('ix_cafe_dash_created_at', table_name='cafe_dash')
    # ### end Alembic commands ###
