"""Added new games Zoopolis, Gangs Wars

Revision ID: cae706dbea3c
Revises: dff9739e68ef
Create Date: 2024-08-30 12:12:33.605867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cae706dbea3c'
down_revision: Union[str, None] = 'dff9739e68ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gangs_wars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promo_code', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gangs_wars_promo_code'), 'gangs_wars', ['promo_code'], unique=False)
    op.create_table('zoopolis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promo_code', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zoopolis_promo_code'), 'zoopolis', ['promo_code'], unique=False)
    op.drop_index('ix_mud_racing_promo_code', table_name='mud_racing')
    op.drop_table('mud_racing')
    op.drop_index('ix_bike_ride_3d_promo_code', table_name='bike_ride_3d')
    op.drop_table('bike_ride_3d')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike_ride_3d',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('promo_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='riding_extreme_3d_pkey')
    )
    op.create_index('ix_bike_ride_3d_promo_code', 'bike_ride_3d', ['promo_code'], unique=False)
    op.create_table('mud_racing',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('promo_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='mud_racing_pkey')
    )
    op.create_index('ix_mud_racing_promo_code', 'mud_racing', ['promo_code'], unique=False)
    op.drop_index(op.f('ix_zoopolis_promo_code'), table_name='zoopolis')
    op.drop_table('zoopolis')
    op.drop_index(op.f('ix_gangs_wars_promo_code'), table_name='gangs_wars')
    op.drop_table('gangs_wars')
    # ### end Alembic commands ###
