"""Added new game CafeDash

Revision ID: dff9739e68ef
Revises: ebe551f9e7e9
Create Date: 2024-08-29 16:02:08.586059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dff9739e68ef'
down_revision: Union[str, None] = 'ebe551f9e7e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafe_dash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promo_code', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cafe_dash_promo_code'), 'cafe_dash', ['promo_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cafe_dash_promo_code'), table_name='cafe_dash')
    op.drop_table('cafe_dash')
    # ### end Alembic commands ###
