"""Added Count Masters

Revision ID: e05720311f72
Revises: 4741561ab172
Create Date: 2024-09-18 12:56:55.992600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e05720311f72'
down_revision: Union[str, None] = '4741561ab172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('count_masters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promo_code', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_count_masters_created_at', 'count_masters', ['created_at'], unique=False)
    op.create_index('ix_count_masters_promo_code', 'count_masters', ['promo_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_count_masters_promo_code', table_name='count_masters')
    op.drop_index('ix_count_masters_created_at', table_name='count_masters')
    op.drop_table('count_masters')
    # ### end Alembic commands ###
