"""Add index to promo_code

Revision ID: ebe551f9e7e9
Revises: 2e561a42af25
Create Date: 2024-08-27 20:02:01.555316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebe551f9e7e9'
down_revision: Union[str, None] = '2e561a42af25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_chain_cube_2048_promo_code', 'chain_cube_2048', ['promo_code'], unique=False)
    op.create_index('ix_merge_away_promo_code', 'merge_away', ['promo_code'], unique=False)
    op.create_index(op.f('ix_mow_and_trim_promo_code'), 'mow_and_trim', ['promo_code'], unique=False)
    op.create_index(op.f('ix_mud_racing_promo_code'), 'mud_racing', ['promo_code'], unique=False)
    op.create_index('ix_polysphere_promo_code', 'polysphere', ['promo_code'], unique=False)
    op.create_index(op.f('ix_train_miner_promo_code'), 'train_miner', ['promo_code'], unique=False)
    op.create_index('ix_twerk_race_3d_promo_code', 'twerk_race_3d', ['promo_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_twerk_race_3d_promo_code', table_name='twerk_race_3d')
    op.drop_index(op.f('ix_train_miner_promo_code'), table_name='train_miner')
    op.drop_index('ix_polysphere_promo_code', table_name='polysphere')
    op.drop_index(op.f('ix_mud_racing_promo_code'), table_name='mud_racing')
    op.drop_index(op.f('ix_mow_and_trim_promo_code'), table_name='mow_and_trim')
    op.drop_index('ix_merge_away_promo_code', table_name='merge_away')
    op.drop_index('ix_chain_cube_2048_promo_code', table_name='chain_cube_2048')
    # ### end Alembic commands ###
