FROM python:3.12.2-slim

RUN apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/*

WORKDIR /hamster

COPY ../requirements-dev.txt requirements-dev.txt

RUN pip install --upgrade pip \
 && pip install -r requirements-dev.txt

COPY .. .